import { Flex, Box, Divider, Text, Image } from "@chakra-ui/react";
import { type NextPage } from "next";
import faceImage from 'public/face.jpeg'
import Head from "next/head";
import Link from "next/link";
import { Source_Sans_Pro, Inter } from 'next/font/google'

import { api } from "~/utils/api";
const SourceSansPro = Source_Sans_Pro({
  subsets: ['latin'],
  weight: "400"
})

const inter = Inter({
  subsets: ['latin'],
  weight: "600"
})

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Home | Sarthak Mangla</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <Flex direction="column" width="70%" className={SourceSansPro.className}>
          <Box textColor="white">
            <Flex direction="row" alignItems="center" gap={3}>
              <Image src={"/face.jpeg"} boxSize='40px'></Image>
              <Text fontSize='1xl' align="center" className={inter.className} fontWeight="bold">Sarthak Mangla</Text>
            </Flex>
            I'm currently studying Computer Science at Purdue.
          </Box>
          <Divider />
          <Box textColor="white">
            Twitter Linkedin whatever
          </Box>
        </Flex>
      </main>
    </>
  );
};

export default Home;
